cluster = {
  "centos" => { :cpus => 2, :mem => 1024 },
}

Vagrant.configure("2") do |config|
  cluster.each_with_index do |(hostname, info), i|

    config.vm.box_check_update = false
    config.vm.synced_folder ".", "/vagrant", type: "rsync",
      rsync__exclude: ".vagrant"
    config.vm.define hostname do |node|
      # base box
      node.vm.box = "generic/centos7"

      # hostname
      node.vm.hostname = hostname

      # provider
      node.vm.provider "parallels" do |p|
        p.check_guest_tools = true
        p.cpus = info[:cpus]
        p.memory = info[:mem]
      end

      # provision
      node.vm.provision "shell",
        :inline => "sudo /bin/bash /vagrant/bootstrap.sh"
    end
  end
end
