Vagrant.configure("2") do |config|
  ## pxe
  config.vm.define "pxeboot" do |node|
    # base box
    node.vm.box = "centos/7"
    node.vm.box_version = "1804.02"

    # hostname
    node.vm.hostname = "pxeboot"

    # provider
    node.vm.provider "libvirt" do |v|
      v.cpus = 2
      v.memory = 4096
    end

    # networks
    node.vm.network :private_network,
      :ip => "192.168.56.100",
      :mac => "fa:16:3e:56:ab:c2"

    # Enable provisioning with a shell script.
    node.vm.provision "shell", inline: "sudo /vagrant/bootstrap.sh"
  end

end
