Vagrant.configure("2") do |config|
  (1..5).each do |i|
    config.vm.define "gaia#{i}" do |node|
      # base box
      node.vm.box = "centos/7"
      node.vm.box_version = "1706.01"

      # provider
      node.vm.provider "virtualbox" do |v|
        v.cpus = 4
        v.memory = 3072
        v.name = "gaia#{i}"
      end

      # hostname
      node.vm.hostname = "gaia#{i}"

      # networks
      node.vm.network "private_network", ip: "192.168.56.#{i+10}"

      # shared directory
      #node.vm.synced_folder "./share", "/home/vagrant/share"

      # Enable provisioning with a shell script.
      node.vm.provision "shell", inline: "sudo /vagrant/bootstrap.sh"
    end
  end
end
