Vagrant.configure("2") do |config|
  ## deploy node
  config.vm.define "ceph-deploy" do |node|
    # base box
    node.vm.box = "centos/7"

    # hostname
    node.vm.hostname = "ceph-deploy"

    # provider
    node.vm.provider "libvirt" do |p|
      p.cpus = 4
      p.memory = 4096
      p.storage :file, :size => '30G', :type => 'qcow2'
    end

    # networks
    node.vm.network :private_network,
      :ip => "192.168.13.#{10+i}"
  end

  ## ceph nodes
  (1..3).each do |i|
    config.vm.define "ceph#{i}" do |node|
      # base box
      node.vm.box = "centos/7"

      # hostname
      node.vm.hostname = "ceph#{i}"

      # provider
      node.vm.provider "libvirt" do |p|
        p.cpus = 2
        p.memory = 2048
        p.storage :file, :size => '30G', :type => 'qcow2'
        p.storage :file, :size => '40G', :type => 'qcow2'
      end

      # networks
      node.vm.network :private_network,
        :ip => "192.168.13.#{10+i}"
    end
  end

end
