Vagrant.configure("2") do |config|

  (1..3).each do |i|
    config.vm.define "hadoop#{i}" do |node|
      # base box
      node.vm.box = "centos/7"

      # hostname
      node.vm.hostname = "hadoop#{i}"

      # provider
      node.vm.provider "libvirt" do |p|
        p.cpus = 4
        p.memory = 4096
        p.storage :file, :size => '40G', :type => 'qcow2'
        p.storage :file, :size => '80G', :type => 'qcow2'
        p.storage :file, :size => '80G', :type => 'qcow2'
      end

      # networks
      node.vm.network :private_network,
        :ip => "192.168.14.#{10+i}"
    end
  end

end
