Vagrant.configure("2") do |config|
  ## master nodes
  (1..1).each do |i|
    config.vm.define "ctrl#{i}" do |node|
      # hostname
      node.vm.hostname = "tstack-con#{i}"

      # provider
      node.vm.provider "libvirt" do |p|
        p.cpus = 4
        p.memory = 4096
        p.boot 'hd'
        p.boot 'cdrom'
        p.mgmt_attach = false
        p.storage :file, :size => '30G', :type => 'qcow2'
        p.storage :file, :size => '40G', :type => 'qcow2'
        p.storage :file, :device => :cdrom, :path => '/data/tstack/TStack-20180927.iso'
      end

      # networks
      node.vm.network :private_network,
        :libvirt__network_name => "tstack-mgmt"

      node.vm.network :private_network,
        :libvirt__network_name => "tstack-ext"
    end
  end

  ## control nodes
  (2..3).each do |i|
    config.vm.define "ctrl#{i}" do |node|
      # hostname
      node.vm.hostname = "tstack-con#{i}"

      # provider
      node.vm.provider "libvirt" do |p|
        p.cpus = 4
        p.memory = 4096
        p.boot 'hd'
        p.boot 'network'
        p.mgmt_attach = false
        p.storage :file, :size => '30G', :type => 'qcow2'
        p.storage :file, :size => '40G', :type => 'qcow2'
      end

      # networks
      node.vm.network :private_network,
        :libvirt__network_name => "tstack-mgmt"

      node.vm.network :private_network,
        :libvirt__network_name => "tstack-ext"
    end
  end

  ## compute nodes
  (1..1).each do |i|
    config.vm.define "compute#{i}" do |node|
      # hostname
      node.vm.hostname = "tstack-compute#{i}"

      # provider
      node.vm.provider "libvirt" do |p|
        p.cpus = 4
        p.memory = 2048
        p.boot 'hd'
        p.boot 'network'
        p.mgmt_attach = false
        p.storage :file, :size => '30G', :type => 'qcow2'
      end

      # networks
      node.vm.network :private_network,
        :libvirt__network_name => "tstack-mgmt"

      node.vm.network :private_network,
        :libvirt__network_name => "tstack-ext"
    end
  end
end
